export default {
  details: 'Details',
  hash: 'Hash',
  block: 'Block',
  age: 'Age',
  when: 'When',
  from: 'From',
  to: 'To',
  tos: 'To',
  type: 'Type',
  amount: 'Amount',
  fee: 'Fee',
  feeValidator: 'Validator Fee',
  stake: 'Stake',
  minStake: 'Min.',
  power: 'Power',
  total: 'Total',
  empty: 'Empty',
  signed: 'Signed',
  missed: 'Missed',
  validator: 'Validator',
  validators: 'Validators',
  candidates: 'Candidates',
  delegators: 'Delegators',
  slots: 'Slots',
  height: 'Height',
  timestamp: 'Timestamp',
  blockTime: 'Block Time',
  blockSize: 'Block Size',
  reward: 'Reward',
  txs: 'Transactions',
  nonce: 'Nonce',
  message: 'Message',
  coinsSold: 'Sold',
  coinsReceived: 'Received',
  viewAll: 'View all',
  bytes: 'bytes',
  coin: 'Coin',
  coins: 'Coins',
  delegated: 'Delegated',
  million: 'mln',
  and: 'and',
  check: 'Check',
  checkIssuer: 'Issuer',
  proof: 'Proof',
  symbol: 'Symbol',
  name: 'Name',
  price: 'Price',
  supply: 'Supply',
  reserveBalance: 'Reserve',
  crr: 'CRR',
  totalVolume: 'Total Volume',
  initialAmount: 'Initial Amount',
  initialReserve: 'Initial Reserve',
  daily: 'for last 24h',
  perDay: 'per day',
  perHour: 'per hour',
  perMinute: 'per minute',
  rating: 'Rating',
  status: 'Status',
  or: 'or',
  any: 'Any',
  all: 'All',
  income: 'Income',
  outcome: 'Outcome',
  coins_created: 'Coins',
  addresses: 'addresses',
  vote: 'Vote',
  votes: 'Votes',
  bipBanker: 'Instant BIP exchange',
  profiles: 'Profiles'
}
