export default {
  title: 'Coins',
  symbol: 'Symbol',
  name: 'Description',
  crr: 'CRR',
  delegated: 'Delegated',
  reserve: 'Reserve',
  volume: 'Volume',
  initialReserve: 'Initial Reserve',
  initialAmount: 'Initial Amount',
  initialPrice: 'Initial Price',
  owner: 'Owner',
  validator: 'Validator',
  price: 'Price',
  karma: 'Karma',
  metadataLink: 'How to change metadata',
  createdAt: 'Created',
  createdTx: 'Transaction',
  lifetime: 'Lifetime',
  deletedAt: 'Deleted',
  now: 'Now'
}
