export default {
  details: 'Подробиці',
  hash: 'Хеш',
  block: 'Блок',
  age: 'Вік',
  when: 'Коли',
  from: 'Відправник',
  to: 'Отримувач',
  tos: 'Адресати',
  type: 'Тип',
  amount: 'Кількість',
  fee: 'Комісія',
  feeValidator: 'Комісія валідатора',
  stake: 'Стейк',
  minStake: 'Мін.',
  power: 'Сила',
  total: 'Всього',
  empty: 'Немає',
  signed: 'Підписаний',
  missed: 'Пропущений',
  validator: 'Валідатор',
  validators: 'Валідатори',
  candidates: 'Кандидати',
  delegators: 'Делегатори',
  slots: 'Слоти',
  height: 'Висота',
  timestamp: 'Час',
  blockTime: 'Час блока',
  blockSize: 'Розмір блока',
  reward: 'Нагороди',
  txs: 'Транзакції',
  nonce: 'Nonce',
  message: 'Повідомлення',
  coinsSold: 'Продано',
  coinsReceived: 'Отримано',
  viewAll: 'Подивитись все',
  bytes: 'байт',
  coin: 'Монета',
  coins: 'Монети',
  million: 'млн',
  and: 'і',
  check: 'Чек',
  checkIssuer: 'Засновник',
  proof: 'Пароль',
  symbol: 'Символ',
  name: 'Назва',
  price: 'Ціна',
  supply: 'Випущено',
  reserveBalance: 'Резерв',
  delegated: 'Делеговано',
  crr: 'CRR',
  totalVolume: 'Загальний обєм',
  initialAmount: 'Емисія',
  initialReserve: 'Резерв',
  daily: 'за добу',
  perDay: 'на протязі дня',
  perHour: 'за годину',
  perMinute: 'за хвилину',
  rating: 'Рейтинг',
  status: 'Статус',
  or: 'чи',
  any: 'Любий',
  all: 'Всі',
  income: 'Вхідні',
  outcome: 'Вихідні',
  coins_created: 'Монети',
  addresses: 'адресів',
  vote: 'Голос',
  votes: 'Голосів',
  bipBanker: 'Миттєвий обмін BIP',
  profiles: 'Профілі'
}
