export default {
  details: 'Podrobnosti',
  hash: 'Хэш',
  block: 'Blok',
  age: 'Staost',
  when: 'Gdaj',
  from: 'Pošiljatelj',
  to: 'Naslovnik',
  tos: 'Naslovniki',
  type: 'Tip',
  amount: 'Količina',
  fee: 'Komisija',
  feeValidator: 'Комиссия валидатора',
  stake: 'Stejk',
  minStake: 'Min.',
  power: 'Moč',
  total: 'Vsega',
  empty: 'Ni',
  signed: 'Podpisan',
  missed: 'Пропущен',
  validator: 'Валидатор',
  validators: 'Potrjevalci',
  candidates: 'Kandidati',
  delegators: 'Делегаторы',
  slots: 'Слоты',
  height: 'Высота',
  timestamp: 'Čas',
  blockTime: 'Время блока',
  blockSize: 'Velikost bloka',
  reward: 'Nagrada',
  txs: 'Transakcije',
  nonce: 'Nonce',
  message: 'Sporočilo',
  coinsSold: 'Prodano',
  coinsReceived: 'Получено',
  viewAll: 'Посмотреть все',
  bytes: 'байт',
  coin: 'Kovanec',
  coins: 'Kovanci',
  million: 'млн',
  and: 'и',
  check: 'Чек',
  checkIssuer: 'Создатель',
  proof: 'Geslo',
  symbol: 'Simbol',
  name: 'Ime',
  price: 'Cena',
  supply: 'Выпущено',
  reserveBalance: 'Резерв',
  delegated: 'Делегировано',
  crr: 'CRR',
  totalVolume: 'Общий объем',
  initialAmount: 'Эмиссия',
  initialReserve: 'Резерв',
  daily: 'за сутки',
  perDay: 'в сутки',
  perHour: 'в час',
  perMinute: 'в Minutу',
  rating: 'Рейтинг',
  status: 'Status',
  or: 'или',
  any: 'Любой',
  all: 'Все',
  income: 'Prerjete',
  outcome: 'Poslane',
  coins_created: 'Kovanci',
  addresses: 'naslovov',
  vote: 'Glas',
  votes: 'Glasov',
  bipBanker: 'Мгновенный обмен BIP',
  profiles: 'Prrofile'
}
