export default {
  details: 'Detalles',
  hash: 'Hash',
  block: 'Bloque',
  age: 'Edad',
  when: 'Cuando',
  from: 'De',
  to: 'A',
  tos: 'A',
  type: 'Tipo',
  amount: 'Cantidad',
  fee: 'Comisión',
  feeValidator: 'Comisión del validado',
  stake: 'Stake',
  minStake: 'Min. Stake',
  power: 'Potencia',
  total: 'Total',
  empty: 'Vacío',
  validator: 'Validado',
  validators: 'Validados',
  candidates: 'Candidatos',
  delegators: 'Delegados',
  slots: 'Slots',
  height: 'Altura',
  timestamp: 'Marca de tiempo',
  blockTime: 'tiempo de bloque',
  blockSize: 'Tamaño de bloque',
  reward: 'Recompensa',
  txs: 'Transacciones',
  nonce: '(Un) nonce',
  message: 'Mensaje',
  coinsSold: 'Vendido',
  coinsReceived: 'Recibido',
  viewAll: 'Ver todo',
  bytes: 'bytes',
  coin: 'Moneda',
  coins: 'Monedas',
  delegated: 'Delegado',
  million: 'millon',
  and: 'y',
  check: 'Cheque',
  checkIssuer: 'editor',
  proof: 'Prueba',
  symbol: 'Símbolo',
  name: 'Nombre',
  price: 'Precio',
  supply: 'Suministro',
  reserveBalance: 'Reserva',
  crr: 'RRC',
  totalVolume: 'Volumen total  /  total ',
  initialAmount: 'Cantidad inicial',
  initialReserve: 'Reserva inicial',
  daily: 'por las últimas 24h',
  perDay: 'por día',
  perHour: 'por hora',
  perMinute: 'por minuto',
  rating: 'Calificación',
  status: 'Estado',
  or: 'o',
  any: 'Alguna',
  all: 'Todas',
  income: 'Entrantes',
  outcome: 'Salientes',
  coins_created: 'Monedas',
  addresses: 'direcciones',
  vote: 'Voto',
  votes: 'Votos',
  bipBanker: 'Intercambio instantáneo de BIP',
  profiles: 'Perfiles'
}
