export default {
  title: 'Kovance',
  symbol: 'Simbol',
  name: 'Opis',
  crr: 'CRR',
  delegated: 'Delegirano',
  reserve: 'Rezerva',
  volume: 'Emisija',
  initialReserve: 'Začetna rezerva',
  initialAmount: 'Začetna emisija',
  initialPrice: 'Začetna cena',
  owner: 'Lastnik',
  validator: 'Potrjevalec',
  price: 'Cena',
  karma: 'Karma',
  metadataLink: 'Kako spremeniti metapodatki',
  createdAt: 'Kreirana',
  createdTx: 'Transakcija',
  lifetime: 'Življenska doba',
  deletedAt: 'Izbrisana ob',
  now: 'Now'
}
