export default {
  title: 'Монеты',
  symbol: 'Символ',
  name: 'Описание',
  crr: 'CRR',
  delegated: 'Делегировано',
  reserve: 'Резерв',
  volume: 'Эмиссия',
  initialReserve: 'Начальный резерв',
  initialAmount: 'Начальная эмиссия',
  initialPrice: 'Начальная цена',
  owner: 'Владелец',
  validator: 'Валидатор',
  price: 'Цена',
  karma: 'Карма',
  metadataLink: 'Как изменить метаданные',
  createdAt: 'Создана',
  createdTx: 'Транзакция',
  lifetime: 'Время жизни',
  deletedAt: 'Удалена',
  now: 'Now'
}
